# Generated by Django 4.2.6 on 2023-11-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='updatedBy',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
